# Generated by Django 4.2.9 on 2026-02-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daohang',
            fields=[
                ('daohang_bianhao', models.AutoField(db_column='dh_id', primary_key=True, serialize=False)),
                ('daohang_bianma', models.CharField(db_column='dh_bm', max_length=120, unique=True)),
                ('daohang_biaoti', models.CharField(db_column='dh_bt', max_length=200)),
                ('leixing_xuanze', models.CharField(choices=[('mulu', '目录类型'), ('caidian', '菜单类型'), ('anniu', '按钮类型')], db_column='lx_xz', default='caidian', max_length=40)),
                ('luyou_dizhi', models.CharField(blank=True, db_column='ly_dz', max_length=800, null=True)),
                ('tubiao_yangshi', models.CharField(blank=True, db_column='tb_ys', max_length=200, null=True)),
                ('paixu_haoma', models.IntegerField(db_column='px_hm', default=0)),
                ('xianshi_zhuangtai', models.IntegerField(choices=[(145, '显示状态'), (48, '隐藏状态')], db_column='xs_zt', default=145)),
                ('chuangjian_shijian', models.DateTimeField(auto_now_add=True, db_column='cj_sj')),
                ('xiugai_shijian', models.DateTimeField(auto_now=True, db_column='xg_sj')),
                ('beizhu_xinxi', models.TextField(blank=True, db_column='bz_xx', null=True)),
                ('fuji_daohang', models.ForeignKey(blank=True, db_column='fj_dh', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ziji_daohang', to='kuangcang.daohang')),
            ],
            options={
                'db_table': 'kuang_daohang',
                'ordering': ['paixu_haoma', 'daohang_bianhao'],
            },
        ),
        migrations.CreateModel(
            name='Juese',
            fields=[
                ('juese_bianhao', models.AutoField(db_column='js_id', primary_key=True, serialize=False)),
                ('juese_daima', models.CharField(db_column='js_dm', max_length=120, unique=True)),
                ('juese_mingcheng', models.CharField(db_column='js_mc', max_length=200)),
                ('dengji_shuzhi', models.IntegerField(db_column='dj_sz', default=888)),
                ('qiyong_zhuangtai', models.IntegerField(choices=[(234, '启用状态'), (56, '禁用状态')], db_column='qy_zt', default=234)),
                ('chuangjian_shijian', models.DateTimeField(auto_now_add=True, db_column='cj_sj')),
                ('xiugai_shijian', models.DateTimeField(auto_now=True, db_column='xg_sj')),
                ('beizhu_xinxi', models.TextField(blank=True, db_column='bz_xx', null=True)),
                ('daohang_guanlian', models.ManyToManyField(blank=True, db_column='dh_gl', related_name='juese_jh', to='kuangcang.daohang')),
            ],
            options={
                'db_table': 'kuang_juese',
                'ordering': ['dengji_shuzhi', '-chuangjian_shijian'],
            },
        ),
        migrations.CreateModel(
            name='Kanche',
            fields=[
                ('kanche_bianhao', models.AutoField(db_column='kc_id', primary_key=True, serialize=False)),
                ('denglu_biaoshi', models.CharField(db_column='dl_bs', max_length=120, unique=True)),
                ('mingcheng_xianshi', models.CharField(db_column='mc_xs', max_length=200)),
                ('jiami_mima', models.CharField(db_column='jm_mm', max_length=800)),
                ('lianxi_dianhua', models.CharField(blank=True, db_column='lx_dh', max_length=40, null=True)),
                ('dianzi_youjian', models.CharField(blank=True, db_column='dz_yj', max_length=200, null=True)),
                ('touxiang_lujing', models.CharField(blank=True, db_column='tx_lj', max_length=800, null=True)),
                ('huodong_zhuangtai', models.IntegerField(choices=[(168, '活跃勘察'), (37, '休眠封存')], db_column='hd_zt', default=168)),
                ('zuijin_denglu', models.DateTimeField(blank=True, db_column='zj_dl', null=True)),
                ('chuangjian_shijian', models.DateTimeField(auto_now_add=True, db_column='cj_sj')),
                ('xiugai_shijian', models.DateTimeField(auto_now=True, db_column='xg_sj')),
                ('beizhu_xinxi', models.TextField(blank=True, db_column='bz_xx', null=True)),
                ('juese_guanlian', models.ManyToManyField(blank=True, db_column='js_gl', related_name='kanche_jh', to='kuangcang.juese')),
            ],
            options={
                'db_table': 'kuang_kanche',
                'ordering': ['-chuangjian_shijian'],
            },
        ),
        migrations.CreateModel(
            name='Caozuo',
            fields=[
                ('caozuo_bianhao', models.AutoField(db_column='cz_id', primary_key=True, serialize=False)),
                ('mokuai_mingcheng', models.CharField(db_column='mk_mc', max_length=200)),
                ('caozuo_leixing', models.CharField(db_column='cz_lx', max_length=120)),
                ('caozuo_miaoshu', models.TextField(db_column='cz_ms')),
                ('qingqiu_fangshi', models.CharField(db_column='qq_fs', max_length=20)),
                ('qingqiu_lujing', models.CharField(db_column='qq_lj', max_length=800)),
                ('qingqiu_ip', models.CharField(db_column='qq_ip', max_length=120)),
                ('caozuo_shijian', models.DateTimeField(auto_now_add=True, db_column='cz_sj')),
                ('kanche_yinyong', models.ForeignKey(db_column='kc_yy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuangcang.kanche')),
            ],
            options={
                'db_table': 'kuang_caozuo',
                'ordering': ['-caozuo_shijian'],
            },
        ),
        migrations.AddIndex(
            model_name='kanche',
            index=models.Index(fields=['denglu_biaoshi'], name='idx_kc_denglu'),
        ),
        migrations.AddIndex(
            model_name='kanche',
            index=models.Index(fields=['huodong_zhuangtai'], name='idx_kc_zhuangtai'),
        ),
        migrations.AddIndex(
            model_name='juese',
            index=models.Index(fields=['juese_daima'], name='idx_js_daima'),
        ),
        migrations.AddIndex(
            model_name='juese',
            index=models.Index(fields=['dengji_shuzhi'], name='idx_js_dengji'),
        ),
        migrations.AddIndex(
            model_name='daohang',
            index=models.Index(fields=['daohang_bianma'], name='idx_dh_bianma'),
        ),
        migrations.AddIndex(
            model_name='daohang',
            index=models.Index(fields=['paixu_haoma'], name='idx_dh_paixu'),
        ),
        migrations.AddIndex(
            model_name='caozuo',
            index=models.Index(fields=['-caozuo_shijian'], name='idx_cz_shijian'),
        ),
    ]
